config/routes.rb
Vvapp::Application.routes.draw do

  get "password_resets/new"
  root 'users#profile'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'submission', to: 'submissions#show', as: 'submission'
  get 'submission/edit', to: 'submissions#edit', as: 'edit_submission'
  patch 'submission', to: 'submissions#update'
  post 'submission/complete', to: 'submissions#complete', as: 'complete_submission'
  resources :submissions, only: [:new, :create]

  get 'submission/images', to: 'submissions#images'
  post 'submission/images', to: 'images#create'
  delete 'submission/images/:id', to: 'images#destroy', as: 'submission_image'

  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  resources :password_resets

  resources :users, only: [:new, :create]
  get "/register", to: "users#new", as: "register"
  get '/profile', to: "users#profile"
  get '/profile/edit', to: "users#edit_profile", as: "edit_profile"
  patch '/profile', to: 'users#update_profile', as: 'update_profile'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :submissions
  # don't validate first_name, so that art groups have a way out
  # similarly don't force gender validation
  # finally, don't force province validation
  validates  :last_name, :email, :phone_number, :street_address, :city, :postal_code, :country, presence: true
  validates :email, uniqueness: true

  has_secure_password

  def has_submission?
    self.submissions.any?
  end

  def recent_submission
    self.submissions.last
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_locale_to_french
  before_action :check_user_login, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to profile_path, notice: "Vous avez réussi à créer votre compte d'utilisateur."
    else
      render :new
    end
  end

  def profile
    @submission = @current_user.recent_submission
  end

  def edit_profile
    @user = @current_user
  end

  def update_profile
    if @current_user.update(user_params)
      redirect_to profile_path, notice: "Vous avez réussi à éditer votre information d'utilisateur."
    else
      @user = @current_user
      render :edit_profile
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :gender, :email, :phone_number, :street_address, :city, :province, :postal_code, :country, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
    <%= form_for @user, url: url, html: {class: 'form-horizontal'} do |f| %>

      <%= f.error_messages %>

      <div class="control-group">
        <%= f.label :first_name, "Prénom", :class => "control-label" %>
        <div class="controls"> <%= f.text_field :first_name %> </div>
      </div>

      <div class="control-group">
        <%= f.label :last_name, "Nom de famille ou de collective d'artiste", :class => "control-label" %>
        <div class="controls"> <%= f.text_field :last_name %> </div>
      </div>

      <div class="control-group">
        <%= f.label :email, "Courriel", :class => "control-label" %>
        <div class="controls"> <%= f.text_field :email%> </div>
      </div>

      <div class="control-group">
        <%= f.label :password, "Mot de passe", :class => "control-label" %>
        <div class="controls"> <%= f.password_field :password %> </div>
      </div>

      <div class="control-group">
        <%= f.label :password_confirmation, "Confirmez mot de passe", :class => "control-label" %>
        <div class="controls"> <%= f.password_field :password_confirmation %> </div>
      </div>

      <div class="control-group">
        <%= f.label :phone_number, "Numéro de téléphone", :class => "control-label" %>
        <div class="controls"> <%= f.text_field :phone_number %> </div>
      </div>

      <div class="control-group">
        <%= f.label :street_address, "Adresse de rue", :class => "control-label" %>
        <div class="controls"> <%= f.text_field :street_address %> </div>
      </div>

      <div class="control-group">
        <%= f.label :city, "Ville", :class => "control-label" %>
        <div class="controls"> <%= f.text_field :city %> </div>
      </div>

      <div class="control-group">
        <%= f.label :province, "Province", :class => "control-label" %>
        <div class="controls"> <%= f.text_field :province %> </div>
      </div>

      <div class="control-group">
        <%= f.label :postal_code, "Code postal", :class => "control-label" %>
        <div class="controls"> <%= f.text_field :postal_code %> </div>
      </div>

      <div class="control-group">
        <%= f.label :country, "Pays", :class => "control-label" %>
        <div class="controls"> <%= f.text_field :country %> </div>
      </div>

      <div class="control-group">
        <div class="controls"><%= f.label :gender_femme, "Femme", :class => "radio inline" %>
        <%= f.radio_button :gender, "Femme" %>
        <%= f.label :gender_homme, "Homme", :class => "radio inline" %>
        <%= f.radio_button :gender, "Homme" %></div>

      </div>


      <div class="control-group">
        <div class="controls"> <%= f.submit submit_text, class: "btn btn-small btn-inverse", id: "Inscription" %> </div>
      </div>

    <% end %>

app/views/users/edit_profile.html.erb
<%= render partial: 'shared/progressbar', locals: { bar_percent: 33, step: "Étape 1 de 3"}%>

<h1>Editer profile pour <%= @current_user.first_name + " " + @current_user.last_name%></h1>

<%= render partial: 'form', locals: { submit_text: 'Enregistrer modifications', url: update_profile_path } %>

app/views/users/new.html.erb
<%= render partial: 'shared/progressbar', locals: { bar_percent: 0, step: "Étape 1 de 3"}%>
<div class="row">
  <div class="span8 display-content">
    <h1>Inscription d'artiste</h1>

      <%= render partial: 'form', locals: { submit_text: 'Inscrivez-vous', url: users_path } %>
  </div>

  <div class="span4 display-content">
     <h2>Déjà inscrit?</h2>
     <p>Si vous êtes déjà inscrit, </p>
     <h2><a href="/login">Connectez-vous</a>
     </h2>
  </div>
</div>

app/views/users/profile.html.erb
<%= render partial: 'shared/progressbar', locals: { bar_percent: 33, step: "Étape 1 de 3"}%>

 <h1>Page profile pour <%= @current_user.first_name + " " + @current_user.last_name%></h1>

  <div class="table-profile">
  <table class="table table-striped">
  <tr>
    <td>Nom: </td>
    <td> <%= @current_user.first_name + " " + @current_user.last_name%></td>
  </tr>

  <tr>
    <td>Courriel: </td>
    <td> <%= @current_user.email %></td>
  </tr>

  <tr>
    <td>Numéro de téléphone: </td>
    <td> <%= @current_user.phone_number %></td>
  </tr>

  <tr>
    <td>Adresse de rue: </td>
    <td> <%= @current_user.street_address %></td>
  </tr>

  <tr>
    <td>Ville: </td>
    <td> <%= @current_user.city %></td>
  </tr>

  <tr>
    <td>Province: </td>
    <td> <%= @current_user.province %></td>
  </tr>

  <tr>
    <td>Code postal: </td>
    <td> <%= @current_user.postal_code %></td>
  </tr>

  <tr>
    <td>Pays: </td>
    <td> <%= @current_user.country %></td>
  </tr>

  <tr>
    <td>Femme/Homme: </td>
    <td> <%= @current_user.gender %></td>
  </tr>
  </table>
  </div>

  <%= link_to raw('<i class="icon-edit"></i> Editer profile'), edit_profile_path,class: "btn btn-small btn-inverse"  %>


  <% if @current_user.has_submission? %>
    <% if @current_user.recent_submission.complete %>
      <%= link_to 'Revisez soumission', submission_path, class: 'btn btn-large btn-primary' %>
    <% else %>
      <%= link_to 'Continuez soumission', submission_path, class: 'btn btn-large btn-primary', id: "link-Continue_Sub" %>
    <% end %>
  <% else %>
    <%= link_to 'Commencez dossier', new_submission_path, class: 'btn btn-large btn-primary' %>
  <% end %>
   </div>