config/routes.rb
Vvapp::Application.routes.draw do

  get "password_resets/new"
  root 'users#profile'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'submission', to: 'submissions#show', as: 'submission'
  get 'submission/edit', to: 'submissions#edit', as: 'edit_submission'
  patch 'submission', to: 'submissions#update'
  post 'submission/complete', to: 'submissions#complete', as: 'complete_submission'
  resources :submissions, only: [:new, :create]

  get 'submission/images', to: 'submissions#images'
  post 'submission/images', to: 'images#create'
  delete 'submission/images/:id', to: 'images#destroy', as: 'submission_image'

  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  resources :password_resets

  resources :users, only: [:new, :create]
  get "/register", to: "users#new", as: "register"
  get '/profile', to: "users#profile"
  get '/profile/edit', to: "users#edit_profile", as: "edit_profile"
  patch '/profile', to: 'users#update_profile', as: 'update_profile'

end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user
  has_many :images

  mount_uploader :cv, DocumentUploader
  mount_uploader :artist_statement, DocumentUploader
  mount_uploader :expo_project, DocumentUploader
  mount_uploader :special_needs, DocumentUploader
  mount_uploader :image_list, DocumentUploader

  validates :cv, :image_list, :artist_statement, presence: true
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_locale_to_french
  before_action :check_user_login
  before_action :get_submission, except: [:new, :create]

  def new
    if @current_user.submissions.size == 1
      redirect_to profile_path, alert: "Vous avez déjà une soumission"
    else
      @submission = Submission.new
    end
  end

  def create
    @submission = @current_user.submissions.build(submission_params)

    if @submission.save
      redirect_to submission_path, notice: "Vos documents ont été reçus!"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @submission.update(submission_params)
      redirect_to submission_path, notice: "Vos documents ont été mis à jour!"
    else
      render :edit
    end
  end

  def images
  end

  def complete
    @submission.complete = true
    @submission.save
    redirect_to profile_path, notice: 'Votre Soumission est complete'
  end

  private
  def get_submission
    @submission = @current_user.recent_submission
  end

  def submission_params
    params.require(:submission).permit(:cv, :artist_statement, :expo_project, :special_needs, :video_link, :image_list, :images_attributes => [:image_file])
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_form.html.erb
<%= form_for @submission, html: {class: 'form-horizontal'} do |f| %>
    <%= f.error_messages %>
  <div class="profile-form">
    <div class="control-group">
      <%= f.label :cv, "CV", :class => "control-label" %>
      <div class="controls"><%= f.file_field :cv %> Curriculum vitae (maximum 2 pages)
      <%= f.hidden_field :cv_cache %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :artist_statement, "Démarche", :class => "control-label" %>
      <div class="controls"><%= f.file_field :artist_statement %> Démarche artistique incluant votre intention de projet (150 mots)
      <%= f.hidden_field :artist_statement_cache %>
      </div>
    </div>

<!--     <div class="control-group">
      <%= f.label :expo_project, "Projet", :class => "control-label" %>
      <div class="controls"><%= f.file_field :expo_project %> Projet d'exposition (une page)
      <%= f.hidden_field :expo_project_cache %>
      </div>
    </div> -->

<!--     <div class="control-group">
      <%= f.label :special_needs, "Exigences spéciales (optionelle)", :class => "control-label" %>
      <div class="controls"><%= f.file_field :special_needs %> Toute exigence spéciale pour l'installation
      <%= f.hidden_field :special_needs_cache %>
      </div>
    </div> -->

    <div class="control-group">
      <%= f.label :image_list, "Liste détaillée de la documentation visuelle", :class => "control-label" %>
      <div class="controls"><%= f.file_field :image_list %> N<sup>o</sup> d'image, Titre, et Annotations
      <%= f.hidden_field :image_list_cache %>
      </div>
    </div>

<!--     <div class="control-group">
      <%= f.label :video_link, "Lien pour soumission video (optionelle SI vous soumettez images)", :class => "control-label" %>
      <div class="controls"><%= f.text_field :video_link %> Lien à votre soumission video (maximum 10 minutes) sur Youtube <a href="http://voixvisuelle.ca/instructions-pour-documentation-video/" target="_blank">Instructions</a>
      </div>
    </div>
 -->
  </div>
  <div class="control-group">
    <div class="controls"> <%= f.submit submit_text,class: "btn btn-small btn-inverse", id: "Submit_submission"  %></div>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<%= render partial: 'shared/progressbar', locals: { bar_percent: 66, step: "Étape 2 de 3"}%>
<h1>Editez soumission pour <%= @submission.user.first_name + " " + @submission.user.last_name%></h1>
<%= render partial: 'form', locals: { submit_text: 'Enregistrer modifications'} %>

app/views/submissions/images.html.erb
<%= render partial: 'shared/progressbar', locals: { bar_percent: 66, step: "Étape 3 de 3"}%>

<p>Utilisez le boutons blanc ou
  glissez-déposez vos fichiers d'image dans la boîte verte qui l'entoure.</p>

<p>En glissant-déposant, plusieurs images peuvent être ajoutés d'un coup. </p>

<div class="alert alert-error"> Veuillez être patient s.v.p.
 Chaque image peut prendre entre plusieurs secondes à une minute pour être uploadé. </div>

<p>Le mode glisser-déposer marche seulement si Javascript est activé dans votre browser.</br>
  (Le cas échéant, il faut utiliser le bouton "Ajouter Images".)</p>

<p>Un dossier doit comprendre un maximum de 10 images numériques.</p>
<p>Les images numériques doivent:</p>
<ul>
  <li>être en format JPEG, avec extension de fichier .jpg </li>
  <li>avoir dimensions minimales 5 x 7 po (ou 7 x 5 po) avec une résolution de 300 dpi</li>
  <li>avoir dimensions maximales 8.5 x 11 po (ou 11 x 8.5 po) avec une résolution de 300 dpi</li>
</ul>
<p>Chaque fichier JPEG doit laisser voir dans ses propriétés, les informations suivantes:
date de la prise de vue; modèle d’appareil photo; temps d’exposition; vitesse iso; focale (soit f0 ou f-). Les fichiers sans propriétés ne seront pas considérés.</p>

<%= form_for [@submission, Image.new], html: {class: 'form-horizontal'} do |f| %>

  <div class="control-group">
    <%= f.label :image_file, "Fichiers d'images", :class => "control-label" %>
    <div class="controls"><%= f.file_field :image_file, multiple: true, name: "image[image_file]" %>
    </div>
  </div>
  <noscript>
    <div class="control-group">
      <div class="controls"> <%= f.submit "Ajouter images", class: "btn btn-small btn-inverse", id: "btn-Submit_Sub" %></div>
    </div>
  </noscript>

<% end %>
<%= button_to 'Finalisez soumission', complete_submission_path, class: "btn btn-primary btn-large  btn-right", id: "btn-Finalize_Sub"%>

<div class="images">
  <%= render @submission.images %>
</div>

app/views/submissions/new.html.erb
<%= render partial: 'shared/progressbar', locals: { bar_percent: 33, step: "Étape 2 de 3"}%>

<h1>Page soumission pour <%= @current_user.first_name + " " + @current_user.last_name%></h1>
<h2>Faites votre soumission de dossier:</h2>
<p>Utilisez les boutons blancs pour ajouter vos documents. Format .pdf ou .doc seulement (de preference .pdf).</p>
<p>Toutes les documents sont requis.</p>
<p>Une page pour soumettre vos images suivra ceci.</p>

<%= render partial: 'form', locals: { submit_text: 'Déposez soumission'} %>

app/views/submissions/show.html.erb
<%= render partial: 'shared/progressbar', locals: { bar_percent: 66, step: "Étape 2 de 3"}%>

<h1>Soumission de <%= @submission.user.first_name + " " + @submission.user.last_name%></h1>

<h2>Documents</h2>

  <div class="table-profile">
  <table class="table table-striped">
  <tr>
    <td><%= link_to 'CV', @submission.cv.url, :target => "_blank" %> </td>
  </tr>

  <tr>
    <td><%= link_to 'Démarche', @submission.artist_statement.url, :target => "_blank" %> </td>
  </tr>
<!--
  <tr>
    <td><%= link_to 'Projet', @submission.expo_project.url, :target => "_blank" %> </td>
  </tr> -->

<!--   <% if @submission.special_needs.file %>
  <tr>
    <td><%= link_to 'Exigences spéciales', @submission.special_needs.url, :target => "_blank" %> </td>
  </tr>
  <% end %> -->

  <% if @submission.image_list.file %>
  <tr>
    <td><%= link_to "Liste d'images", @submission.image_list.url, :target => "_blank" %> </td>
  </tr>
  <% end %>

<!--   <% if @submission.video_link %>
  <tr>
    <td><%= link_to "Lien video", @submission.video_link, :target => "_blank" %> </td>
  </tr>
  <% end %> -->

</table>
</div>

<%= link_to raw('<i class="icon-edit"></i> Editez soumission'), edit_submission_path, class: "btn btn-small btn-inverse", id: "link-Edit_Sub"%>

<%= link_to 'Ajoutez images', submission_images_path, class: "btn btn-primary btn-large", id: "link-Add_Images"%>