config/routes.rb
Vvapp::Application.routes.draw do

  get "password_resets/new"
  root 'users#profile'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'submission', to: 'submissions#show', as: 'submission'
  get 'submission/edit', to: 'submissions#edit', as: 'edit_submission'
  patch 'submission', to: 'submissions#update'
  post 'submission/complete', to: 'submissions#complete', as: 'complete_submission'
  resources :submissions, only: [:new, :create]

  get 'submission/images', to: 'submissions#images'
  post 'submission/images', to: 'images#create'
  delete 'submission/images/:id', to: 'images#destroy', as: 'submission_image'

  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  resources :password_resets

  resources :users, only: [:new, :create]
  get "/register", to: "users#new", as: "register"
  get '/profile', to: "users#profile"
  get '/profile/edit', to: "users#edit_profile", as: "edit_profile"
  patch '/profile', to: 'users#update_profile', as: 'update_profile'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vvapp</title>
  <%= stylesheet_link_tag  "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <h1 id="site-title">
    <span>
      Voix Visuelle
    </span>
  </h1>
  <div id="site-description"><a href="http://voixvisuelle.ca/" target="_blank">Le Centre d'artistes Voix Visuelle</a></div>
</div>
<div class="container">
  <div class="projets">
    <h1> Triennale du sténopé numérique (2e édition) </h1>
  </div>
  <div class="navbar navbar-inverse">
    <div class="navbar-inner">
      <ul class="nav">
      <% if @current_user %>
      <% safe_test = @current_user.has_submission? && @current_user.recent_submission.complete %>
        <% if safe_test %>
          <li class="<%= 'active' if current_page?('/submission/images') %>"><a href="/submission/images">Retournez aux images</a></li>
        <% end %>

        <% if current_page?('/submission/images') || safe_test %>
          <li class="<%= 'active' if current_page?('/submission') %>"><a href="/submission">Retournez aux documents</a></li>
        <% end %>
        <% if !current_page?('/profile') || safe_test %>
          <li class="<%= 'active' if current_page?('/profile') %>"><a href="/profile">Profile</a></li>
        <% end %>
        <li><a href="/logout">Se déconnecter</a></li>
      <% else %>
          <li class="<%= 'active' if current_page?(register_path) %>"><a href="/register">Inscrivez-vous</a></li>
          <li class="<%= 'active' if current_page?(login_path) %>"><a href="/login">Connectez-vous</a></li>
      <% end %>
      </ul>
    </div>
  </div>

  <% if notice %>
    <p class="notice alert alert-success"><%= notice %></p>
  <% end %>

  <% if alert %>
    <p class="alert alert-error"><%= alert %></p>
  <% end %>

  <%= yield %>
</div>

</body>
</html>